version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
    ports:
      - "19006:19006"
      - "19001:19001"
      - "19002:19002"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

  mongo:
    build:
      context: ./mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
